# Generated by Django 3.2.7 on 2021-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=150)),
                ('Lançamento', models.IntegerField()),
            ],
        ),
    ]
